apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgres-secret
  namespace: sonarqube
type: Opaque
stringData:
  POSTGRES_DB: sonarqube
  POSTGRES_USER: sonarqube
  POSTGRES_PASSWORD: change-me-postgres-password
