apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
stringData:
  SONAR_JDBC_USERNAME: sonarqube
  SONAR_JDBC_PASSWORD: change-me-postgres-password
  SONAR_JDBC_URL: jdbc:postgresql://sonarqube-postgres.sonarqube.svc.cluster.local:5432/sonarqube
