sonar.projectKey=sonar-k8s-demo
sonar.projectName=sonar-k8s-demo
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
