apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
type: Opaque
stringData:
  SONAR_JDBC_URL: jdbc:postgresql://sonarqube-postgres:5432/sonarqube
  SONAR_JDBC_USERNAME: sonar
  SONAR_JDBC_PASSWORD: change-me-postgres-password
