apiVersion: v1
kind: Namespace
metadata:
  name: upload-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploader-local-pvc
  namespace: upload-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-openebs-local
  namespace: upload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader-openebs-local
  template:
    metadata:
      labels:
        app: uploader-openebs-local
    spec:
      containers:
      - name: app
        image: go-file-uploader:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_TITLE
          value: Go File Uploader - OpenEBS Local PV
        - name: ACCESS_NOTE
          value: Files are stored on OpenEBS Local PV using hostpath. Data survives pod restart, but this is node-local storage.
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: uploads
          mountPath: /data/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploader-local-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uploader-openebs-local
  namespace: upload-demo
spec:
  selector:
    app: uploader-openebs-local
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30084
  type: NodePort